#!/bin/bash

# vars
BOX_RAW="/mnt/box-raw"
BOX="/mnt/box"
ENCFS_PASS=""
TARGETS="/tank/test"
HETZNER_API_USER=""
HETZNER_API_PASS=""
STORAGEBOX_ID=""
STORAGEBOX_USER=""

source /etc/hetzner-backup/config

# functions
function try {
  eval $*
  if [[ $? != 0 ]]; then
    echo "failed: $*"
    exit 1
  fi
}

# unmount
if mount | grep " $BOX " > /dev/null; then
  try umount "$BOX"
fi
if mount | grep " $BOX_RAW " > /dev/null; then
  try umount "$BOX_RAW"
fi

# mount
try "sshfs -o reconnect,allow_other,noatime $STORAGEBOX_USER@$STORAGEBOX_USER.your-storagebox.de:/ $BOX_RAW"
try 'echo "$ENCFS_PASS" | encfs --stdinpass -o allow_other,noatime $BOX_RAW $BOX'

# upload
try 'cd "$BOX"'
while read -r target; do
  if [[ "$target" == "" ]]; then continue; fi
  while [[ "true" ]]; do
    rsync -PREva "$target" "$BOX"
    if [[ $? == 0 ]]; then break; fi
    sleep 30
  done
done <<< "$TARGETS"

# create snapshot
LAST_SNAPSHOT_DATE=$(curl --user "$HETZNER_API_USER":"$HETZNER_API_PASS"  https://robot-ws.your-server.de/storagebox/"$STORAGEBOX_ID"/snapshot | jq ".[-1].snapshot.timestamp" | tr -d \")
LAST_SNAPSHOT_TIMESTAMP=$(date --date="$LAST_SNAPSHOT_DATE" +%s)
NOW=$(date +%s)
LAST_SNAPHOT_DAYS_OLD=$(expr $(expr $(date +%s) - "$LAST_SNAPSHOT_TIMESTAMP") / 86400)

if [[ "$LAST_SNAPHOT_DAYS_OLD" -gt -1 ]]; then
  FIRST_SNAPSHOT_NAME=$(curl --user "$HETZNER_API_USER":"$HETZNER_API_PASS"  https://robot-ws.your-server.de/storagebox/"$STORAGEBOX_ID"/snapshot | jq ".[0].snapshot.name" | tr -d \")
  curl -X DELETE --user "$HETZNER_API_USER":"$HETZNER_API_PASS"  https://robot-ws.your-server.de/storagebox/"$STORAGEBOX_ID"/snapshot/"$FIRST_SNAPSHOT_NAME"
  curl -X POST --user "$HETZNER_API_USER":"$HETZNER_API_PASS"  https://robot-ws.your-server.de/storagebox/"$STORAGEBOX_ID"/snapshot
fi


